DC_NAME: krm
VM_FOLDER: tala
VM_TEMPLATE: template-UbuS24-1
ESXI_NAME: 172.27.103.111
DISK_SIZE: 100
DATASTORE_NAME: SSD-2TB
MEMORY_SIZE: 8192
CPU_SIZE: 6
NETWORK_NAME: vlan175
IPADDRESS: 192.168.175.106
SUBNET_MASK: 255.255.255.0
GATEWAY: 192.168.175.2
DOMAIN: talapanah.ir
DNS_SERVER1: 8.8.8.8
DNS_SERVER2: 4.2.2.4
