VM_FOLDER: zaraavand
ESXI_NAME: 172.27.103.111
DISK_SIZE: 80
DATASTORE_NAME: SAS1TB-1
MEMORY_SIZE: 8192
CPU_SIZE: 6
NETWORK_NAME: Pfsense
IPADDRESS: 192.168.174.14
DNS_SERVER1: 8.8.8.8
DNS_SERVER2: 4.2.2.4
